title = "Início"
baseURL = "https://prdm0.rbind.io"
languageCode = "pt"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true

[author]
  name = "Pedro Rafael"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

#[[menu.main]]
#    name = "Artigos"
#    url = "/papers/"

[params]
  favicon = "/images/bullterrier.png"
  custom_css = ["css/custom.css"]
  site_logo = "/images/logo_02.svg"
  description = "Aqui você encontrará um pouco do meu trabalho ..."
  facebook = ""
  twitter = "https://twitter.com/Pedro_Rafael1"
  instagram = "https://www.instagram.com/prdm.0/"
  youtube = ""
  github = "https://github.com/prdm0"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/me_04.jpg"
  recent_posts_number = 1
  toc = true
