title = "Início"
baseURL = "https://prdm0.netlify.app"
languageCode = "pt"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[author]
  name = "Pedro Rafael"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Aqui você encontrará um pouco do meu trabalho ..."
  facebook = ""
  twitter = "https://twitter.com/Pedro_Rafael1"
  instagram = "https://www.instagram.com/prdm.0/"
  youtube = ""
  github = "https://github.com/prdm0"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/me_04.jpg"
  recent_posts_number = 2
